### ISSUE TITLE
Which TLS version is being used for requests?

### ISSUE THREAD

**Issue by molokov** [rossp/django-pinpayments#14]
I'm not certain that this *is* an issue, but given that PIN payments are no longer accepting TLS 1.0 as of 1 Jan, 2017, is there a way to easily confirm that the way that django-pinpayments does its requests to PIN's API is using TLS 1.2 (for preference)?

I've seen that you're using the python requests library, which seems to support the later TLS versions for Python 2.7.x and 3.x, but is there anything we should do within the django-pinpayments module to ensure that TLS 1.0 is not used as the encryption method for requests to PIN?

**Comment by rossp** [comment]
Should be OK for Python 2.7+, so we will need to update our requirements (most Django installs should be on 2.7+ anyway I think?). Further we can force it to ignore TLS 1.0 using http://docs.python-requests.org/en/latest/user/advanced/#example-specific-ssl-version

**Comment by rossp** [comment]
In some recent testing it's definitely using TLS 1.2 when on Python 3.
