### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by sirb0rab0g1** [rossp/django-pinpayments#18]
how to use this ? 

im currently in django 2.1 and where the imports documentation was not clear thanks

**Comment by rossp** [comment]
I’m sorry, I don’t understand your question. Cal you please clarify?

That said - I do not actively use this library and have not tested it on recent versions of Django, which unfortunately means it may or may not work easily.

**Comment by sirb0rab0g1** [comment]
ahh sorry. i disregard django pinpayments implementation and use requests in python
